import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { getIsSsrMobile } from "@/hooks/isMobile";
import { SsrMobileProvider } from "@/context/mobile";

export const merchant = localFont({
  src: [
    {
      path: "../../public/fonts/merchant-variable.ttf",
    },
  ],
  variable: "--font-merchant",
});

export const outfit = localFont({
  src: [
    {
      path: "../../public/fonts/outfit-variable.ttf",
    },
  ],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: any) {
  const isMobile = getIsSsrMobile();
  return (
    <html lang="en">
      <SsrMobileProvider value={isMobile}>
        <body
          className={`${merchant.variable} ${outfit.variable} ${outfit.className}`}
        >
          {props.children}
        </body>
      </SsrMobileProvider>
    </html>
  );
}
